language: scala

scala:
  - 2.12.4
  - 2.11.12

sudo: false
script: $TRAVIS_BUILD_DIR/travis/script/build.sh

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sed -i 's/git@github.com:/https:\/\/github.com\//' api/auth-basic-service-api/.gitmodules
  - git submodule update --init --recursive

env:
  global:
  - secure: l0LVQNTw87gecqsumPrTP4e1L7mU2nyXqkdPa2X+KAMfbWnCAN04+UpcDOWkLrFk7PMt3abwQX7X5UcSYFpsJFCJrwnUWJb1ZBtTuF5njpgzrxwtXX0pRl3WqyeyFpcADVdEMv1M6yUwDtkYvUAAx314jXZ0eYhNaUZvcMw29fuy4WJ765ChU3CTQYaKi/932PYZQaaitBY5tfPtbOLv9VziH8dkjBVxW4ShsvhMNbP8Sf1qrLwDccm3klcCKOOLH/3lB7BdTVcsliXzytQ4thN5hcE+u1DlrnssS/bfzPs6Vg7EeXbQxNMa9d1xNlLeENGbQKk1PrlqcHup2WrQsamTlTAJTXKYlzWl/5fb4QyAAJd45sZGbjbgPL+qrFl3e70V0cR8xskssS/D445TQd4jQ6YBqwNjsqhM1hVvL24FNIoRrFD6OkM3C+IbCeBWi5XSt0AKjdZDbXIPbVinh4/pHO0lN0uyZfRGIxbcmla2Mw1hGO5xCdTZOkhB6p1NnjsHFqN6wwQhOoQZ7Q2KGxxG86ob65EH1c32V3EOhfnXk9jd2fOndNom6g67KO+xs7BTRyEtLTM3hGb1mLiVCrOkxJA3NfgK2YWztRZY8vMM0n12cjvh/rBdVYWI+TjkFDYCLRsn/YIJa/Fg0F5G0MFkYW7PW6Y70/MwHjCZ2j8=
  - secure: GNBeCrMWrGEmlhDPv5xL6B5JAL8Yx1giGQYxmLLUYtADtbQrHehN5K7PkMtVOwoHERgTVSJ47nB8bdoQEnd64QAnf6zVsqnRjtoS3/4ulGNw+uJHdK9BpEZn2gb6nIwuPAuvTNNmBeTMGOO+XBFqkGCi2dW2bpS+RhlwW9VXJqJ7/QfDL7i5MMntcCbZWCA2z3kZQEwXVplv2Py8Lcg+G1AkIefkgFx08IwEVgFJzYpUtVBg4moz//SAJoladX6+NhQSNYISXPwA6ZcnIUgYCPQbIUrtRh0oN5EZFh5hzsMh3pbiygZrQCRVb7jO2JD5IZcnp2Xy9xOz9RLCQBC0OtSSXF6KkwsiHEus7EZQikpyzNxK/4dlmJdowe7CgLnzPQ1Zcz7SnuEOD3RvV/EZUZTMPShy9YIOBtPRll2JTJGRGhxeGTI7zNAkkNd6mzW7rnePBJBsFv4YppTmsvSoP+B9fqVWWskDDcVamGlM/cvIZZxpXsx3orO/aeq9OcjOGhYeTUum/dyaIXD444aUrh41k6WBSliHYuSXElsXWpTr7txNGvlxQu2BXIYAMpJOY1reeE0u/WypBOh4J4j4kmT+KNB/WjJSBQPZbp6gbcVJnKaE9ZwzOgesFzlOXMSWPUxeq9Dbfs3rsU6doAEzxSVvwW8HzVy6TOkHOobraC8=
  - secure: mb6yU7DSVB9yIk3jfwUmm7rQIBB6bdzewtpTGwqC5RkW44wdPdUjguBrM0sRAo8Qmc8M230gULtWy8RoxvDPgTEX7VBFtKhYQXcJk2TZXh5MyTnXIjIr9GDH4A7s1NSaPF3RgDQVwU9sW1wg5s/jfGViFhVLrJ0TjubyEku8dqc1uP5/8bkIx84ITsWLq1h5xVJOfQIbdl7id44GrRyH3igBDfSEDuvTpJooqfYiAKYJJM808v4BLQalUMHaNN6LoBeKLs1NE927NB3qWHXhA6FcoAt7uXtMfkRf1HqkW46GDxlf79WtpW2m1ym4Sw2V6cSo2zaltMXxsRKJoKnGToGTSEyRaulCDy8s/xwMfgHbEZbiajlszrGVDltGrwvVMeU1cvoxi9SVNx6Oh9KK94x5NYEa08QeYx+4Zvd7nni96wZtEI879d8t9YJCpVKG+YW9ln/CAE+u1U2Sh8UJVLmpST63NuRv3SiicpRXnVslSR06rCIQy8nH80TWigaERy52xprpGNmLLzQYDB8IWvmjjm8cJsaOnA3aSoFMrc8SgzcYBkDedroNwv68yjJoyOjyztAdC2Z2rgmArsKZS8rJU6yUkwb1N4p50SibDVlpUK+hAzh6bQDoyx4z6Gx7M+txjsoEdkHfIf3++RA4nQdZoikroCfgPxD1ikDnenM=
  - secure: dn7Nq5ZYqcBRfjPLFWT48xBr6Os4brxu+4ShYGlz4eIkZp7R904jiuHKRPTK8B9GFcJecMn13yeiOCP/Oa16D0rXQKlONGsKAMzzlJ8adEgnWsRgxE4W9KZDpWrv/56/S3rDuJVB2pDjH58XXN0Yrk0xmljLPkqytAPQOkx2YX3oA7nLf1sRNO+KqW0RxNOcGwo06EIA8E3cbxSlrZdIQcHCFvd/cE8ge9sCsEFbVWowr47pwvfhcgmJLS+TeiB89ueBXTU8JjQ2YOCvIhOP2eNc96bXQYw+lJlx3oVEYiWFOzBfVqhQcy3nDFtd6GJsFQEO+ywa3DzgX/DL3nAnGKyMWxBENFUxJhydCksC+Lp0l9CQXbhafv8dReIvMtnI2iz0vCZVCaBNMEMmiiXNKZuApWKpMfQCqx3REdQcC3ShH4O3jNHhdQoAg2KHW0uMliZhlGfbilsObcVPtEOtOh6KZSJ/JKRKF3mmxYyWt95j/Z+NLavPTpMbEXFI/GJ6BKj+owAr+FFLx/S72rsCjA5LygWIFus+9BSIdM5c75YlOPr2V83Xp2Lev4al7WR1Cvg3LfyNTJ+SPWNjfE92ojke3iFfuv4i/emrCP1Xji3mbiXDZeqy5w5b4p8B6vdfETGeoDgGQKFcBXLt4pUzjVU0Iixg6b/or9Du+woA/Lo=
